cache:
  directories:
    - $HOME/.m2
install: true
language: java
jdk:
- oraclejdk8
os:
  - linux
env:
  matrix:
    - NEO4J_VERSION=3.1.5
    - NEO4J_VERSION=3.2.2
before_install:
  - openssl aes-256-cbc -K $encrypted_7c9a96972884_key -iv $encrypted_7c9a96972884_iv -in .travisdeploykey.enc -out .travisdeploykey -d
script: "mvn clean test -Dneo4j.version=${NEO4J_VERSION}"
after_success:
  - git config --global user.email "travis@bsimard.com"
  - git config --global user.name "Travis CI"
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travisdeploykey
  - ssh-add .travisdeploykey
  - if [[ "$TRAVIS_PULL_REQUEST" = "false"  && "$NEO4J_VERSION" == "3.2.2" && "$TRAVIS_JDK_VERSION" == "oraclejdk8" &&  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then mvn clean package site; fi
  - if [[ "$TRAVIS_PULL_REQUEST" = "false"  && "$NEO4J_VERSION" == "3.2.2" && "$TRAVIS_JDK_VERSION" == "oraclejdk8" &&  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then mvn clean cobertura:cobertura coveralls:report -Pcoverage -Dcoverall.token=$COVERALL_TOKEN; fi
notifications:
  email:
    on_success: never
    on_failure: change
